# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.define "master", primary: true do |master|
     master.vm.hostname = "master.local"
     master.vm.network "private_network", ip: "192.168.50.201"
     master.vm.network "forwarded_port", guest: 9090, host: 9090
     master.vm.network "forwarded_port", guest: 9091, host: 9091
     master.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
     master.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'manifests'
        puppet.manifest_file = 'master.pp'
     end
  end

  config.vm.define "node1" do |node1|
     node1.vm.hostname = 'node1.local'
     node1.vm.network "private_network", ip: '192.168.50.101'
     node1.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
     node1.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'manifests'
        puppet.manifest_file = 'slave.pp'
     end
  end

  config.vm.define :node2 do |node2|
     node2.vm.hostname = 'node2.local'
     node2.vm.network "private_network", ip: '192.168.50.102'
     node2.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
     node2.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'manifests'
        puppet.manifest_file = 'slave.pp'
     end
  end
end
