# .travis.yml
language: C
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install rsync"
  - "sudo apt-get install curl"
#install:
#  - "bash getfiles.bash"
#before_script:
#  - "mysql -e 'create database myapp_test;'"
script:
  - "bash getfiles.bash"
  - "bash test.bash"
#after_success:
#after_failure:
#notifications:
