# .travis.yml
sudo: false
language: C
addons:
  apt:
    packages:
    - rsync
    - curl
#install:
#  - "bash getfiles.bash"
#before_script:
#  - "mysql -e 'create database myapp_test;'"
script:
  - "bash getfiles.bash"
  - "bash test.bash"
#after_success:
#after_failure:
#notifications:
