# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  
  config.vm.define "master" do |master|
     master.vm.hostname = "master"
     master.vm.network "private_network", ip: "192.168.50.201"
     master.vm.network "forwarded_port", guest: 9090, host: 9090
     master.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
     end
     master.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'manifests'
        puppet.manifest_file = 'master.pp'
     end
  end

  config.vm.define "node01" do |node01|
     node01.vm.hostname = 'node01'
     node01.vm.network "private_network", ip: '192.168.50.101'
     node01.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
     node01.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'manifests'
        puppet.manifest_file = 'slave.pp'
     end
  end

  config.vm.define :node02 do |node02|
     node02.vm.hostname = 'node02'
     node02.vm.network "private_network", ip: '192.168.50.102'
     node02.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
     end
     node02.vm.provision :puppet do |puppet|
        puppet.manifests_path = 'manifests'
        puppet.manifest_file = 'slave.pp'
     end
  end
end
